run_mode: train # train, validate or both
data_generator:
  feature_dir: "features"
  input_size: 4
data_preprocess:
  input_dir: "data"
  output_dir: "features/"
model:
  epochs: 80
  lr: 1e-3
general:
  seed: 10
logging: 
  save_path: ./models_checkpoints
ckp_path: ./models_checkpoints/trained_sleep_lstm.pth #path to ckpt for resume or null
